import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./providers";
import { poppins } from "@/configs/font";
import { cn } from "@/lib/utils";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "text-sm scrollbar")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
